version: 2.9.2.{build}
os: Visual Studio 2017
configuration: Debug
platform: Any CPU

branches:
  only:
  - master

skip_tags: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: bY3HMQXJsuuHTqtDx878B8dh+vRw8Sr+ffu+i2ycNlnvN3NUsGXVCj/SUBlbsNdL

install:
- cmd: git submodule update --init --recursive
- cmd: dotnet restore MimeKit.sln

build:
  project: MimeKit.sln
  verbosity: minimal
  parallel: true

test_script:
- ps: >-
    $NUnitConsoleRunner = Join-Path $Home ".nuget\packages\nunit.consolerunner\3.11.1\tools\nunit3-console.exe"

    $Coveralls = Join-Path $Home ".nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe"

    $OpenCoverDir = Join-Path $Home ".nuget\packages\opencover\4.6.519\tools"

    $OpenCoverProfiler32 = Join-Path $OpenCoverDir "x86\OpenCover.Profiler.dll"

    $OpenCoverProfiler64 = Join-Path $OpenCoverDir "x64\OpenCover.Profiler.dll"

    $OpenCover = Join-Path $OpenCoverDir "OpenCover.Console.exe"

    $OutputDir = "UnitTests\bin\Debug\net48"

    & regsvr32 $OpenCoverProfiler32

    & regsvr32 $OpenCoverProfiler64

    & $OpenCover -filter:"+[MimeKit]* -[UnitTests]*" -target:"$NUnitConsoleRunner" -targetdir:"$OutputDir" -targetargs:"--domain:single UnitTests.dll" -output:opencover.xml

    & $Coveralls --opencover -i opencover.xml --repoToken $Env:COVERALLS_REPO_TOKEN --useRelativePaths --basePath $OutputDir --commitId $Env:APPVEYOR_REPO_COMMIT --commitBranch $Env:APPVEYOR_REPO_BRANCH --commitAuthor $Env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $Env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $Env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $Env:APPVEYOR_BUILD_NUMBER --serviceName appveyor